language: bash

sudo: required

services:
  - docker

script:
  # - '[ "${TRAVIS_PULL_REQUEST_BRANCH}" = "" && "${TRAVIS_PULL_REQUEST}" = "false" ] && make deploy || make lint_the_things'
  - env
  - 'if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make deploy; else make lint_the_things; fi'


# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle


# push directly to master:
#TRAVIS_BRANCH = master
# TRAVIS_PULL_REQUEST=false


# push to feature branch:
# TRAVIS_BRANCH=prs
# TRAVIS_PULL_REQUEST=false

# building pr:
# TRAVIS_BRANCH=master
# TRAVIS_PULL_REQUEST=3

notifications:
  slack:
    secure: t1Zt7fEMVKWNv52tO8ksurA9Ts1IW+U4tfnfR6dJ00oogk34783pEresuBRb0yhUyDF4A4I9ZqNAGjJFBMknh9ZZwEH1WSRb/7lv8pjXFA6PNzxex9Q7VPPeOWGfeIf4MWCKk7JNcFxp0NM/fnlWa6r7Frht3x27BWAKUjO3P2vFxw+Vqyl+st9wWu63RIFVnpDpBOelyLSNTS0K1MBG7NYwYdITUV95CRPxveVlC98LBep1iUjR6xIv4kCTTRUhqhssgkK9yqlTPQNzOb5b8MCRahQwWUiCTp5NCRZQX81+7hUfmNO//y8gRb8PC1OD89k5Sz6vlT9lYwdg+RD8tC2MPZJszGiDGy/gzA3g9bX/bUzUp/RxWD+1tWsCE1w6EKWvDIjULbX259PraDxp7uR4oDS0KSMoUOi/NGQpZv6R4YroenHoXCWRamL4RiU1pNWZ2W5MzMXMtuDd3UHZRJd9DGUgTSYXsyHyYIRFzi8e2zUSZqKOlBbRwoRd2LZ+S//GpJ3si73qS9EORNZMMIFuROzi5ai2xYczRRn+dx79U6OuLyM8Uh8fRvrdqOpLePX1ng+dkKIZI8hlSCTb3bKKKkEot2+1BfGBa1OZkMJYQ4Ff/3FT5jq+OQMHSBfOo1MbEX/by5aWQWS0ENQz45h9mU39o5Teks+ahaJq/Fk=
    # rooms:

    #   - secure: "TSAhcDPk36YFQrRBmtLOrkToezFks9uuB0Y7XeU0En5VAkGMmsBNHz/95eWsnmignu7Tqte4i9gTEIvWA2UkF13RRiOQjeSIQtxkvVFDlzsimRfJ91RotXlI38T1kx8Yp/bQsLggtfAinjPq7GU2kfS3sWQxS5L3zkYpZB3O3r0fR5Cz81+W1sw+Wh13MZzFn5z8IYQQ0a+ahTQ/f/Kg43MkuvhNTcgqcu1MuCfyeTfcDusvLzYTXCQePSBVjPKefItwlk/cwrBrm2Ad4GOG6CW/yBDkR10oZQEQ0/mMC1I0JEGGTTqbk8k/HsuHOLLDa/f8EChA7OpxDe+ucn/vWRZYXofbGVheIrymv4I5iHfEqzGdX1CxTghpt8WpL6J20rm+4QeOAvSf2hQUpen2jjd89HyiGFH4eHM9M3PBQErONZY0nwlQS39eq3C1So/TRQNBluaL3UsyWC6JVbESva1F1wzHtpzQPjkndLoOeTslWK9vxEVLjxUu+Itl7Q9Gos88pqw2g+NhjxlLkkyWYjCS8A8mPcxSuaGNh+n07zsrZg+Bo5XHEC9LpCBPxS1nmvlQz6W9gk0nWavtVMFH09ZOm/Qd67y5Eq3T5oeluxsl82dpBjNN8CoVqulWJMQZ2B/T4uzJT5ck/u9SUpn7AatmUG3jVF9TtWfB5ReAkDY="
