language: bash
sudo: required
services:
- docker
script:
- env
- if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
  make deploy; else make lint_the_things; fi

notifications:
  email: false
  slack:
    secure: "u9dUiIJitGM73iKw1EOcC7kclsKFfTKZJthCGZgBuqTvNRrizN7z6OYrXZGdLeFJQgHyPqUr+j0Te/eUy6B7Cze2zIJGOiYAZyofV75kgqSnEKvNlEVnRle0/yZdq4rwCBkhvb6ry/NJEA2hvSJmuByamnTe95EnEed48kQaP0Mf/GHYvbNTNUnG5P0ptjrohrqgyUSgVk8gloJcZJIqKtzmFlRHQeRddmsiokHZfU6V1YEjdTOMs1FdK+24kYwyfq36dYdCxDybMLq7KY51mLumZ2gauBXD52WZN7m1e0iyHKAxljyq+iYjMWvjcSNQuzvmWMguvSAH2XtU19i+G/FNoV8sZQxv40l0PPXQ/h6wDtPZkxXqJLm0PZeNICrmkCDwPJ5aaBlWjzt3iGyFETg+bGiIduB4Ft8nKwIn3hkAGrC7++S1YY6TWKwfwbccwISKAUXM1bad28hljDiGN9cXvzthxYr1wuTRcBqHd+kABU/XmPQLdGqehamFyf5Hl9Yndc6hivCkJyGgeCXdQmftLCjE+gJkLXvvUusunD0FPaWj0+G1/S4ga/8QgrMsW8pwruiB2k4mF3ahTeg843Wem4jcS3embBqKuHYmwRfTT1WzbsPM/+62Y9+JLrEAmrXILNUE8o+PBW14IVOnMjKh5WGhJolK2oS/zHQkO2c="
