language: bash

sudo: required

services:
  - docker

script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && make deploy || make lint_the_things'

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
