language: bash

script:
- make push

notifications:
  email: false
  slack:
    secure: KKnxOgni+HKQC5A7w3xDJzqnpQ4CRdkI/FLyIeWZ0cwJSaYRkZf30Fs5b6hpdYZ+oej+Hn3dcSr/gwmdVSYmfIpfqtB1om51mMvPYrIa+k1CsNTszMkRvQkQHqWkIxklhpiI9P6/gucR/bhdYkzrPP5icA6bqFK155XvjrYZUj65xsuZG4KZrwPxBNNkVB9tMyFazP2kjGdADgauyaHi2wVUats6DAeKPlfP/8WmSCB7MsiANv0GlmR+qTjbaYmIZHmUU1VSxTyXmfAwgVoU/4zrc5ve5urfyv70nGme+qxDyHiY5sRl9xPmkMIuK/TK4N7q++n+wltKcuEyhfABfhG3T/mDyt5Sfa8ApSkLoWhcsxiYH3Kb9PKpjBMo5o3rG4KsGZP1BOYNQiPewkOeBkmeoIoF5/+qA0rUk+IIewC//4zhFh1J96PSQRFAlUB3Bl0vOo1jiJUshGt4tayvbrpipNSOxB4FsHLdVXHGCLFe79WLw1+OrKtSd4VUzcdfEbaawa58bd0Trlr8p1W9r1bB8PWReVaxbyLxk7h5NwAOut0LNK3IDwgQYIY5n4mbmnZQIoez7BUYmy4wXtGeajUfVc03+Ju/PFp6GMiydaoDEcAHkY5t/cnenuiOucAz1M0OtUHzyUxG/vOGvJkOp5v9ZfMrF53ZEvpyF+mbQ4I=

env:
  global:
    - secure: "IGNC/THmxGt5keuDh5Iir/I/QDzrz/3E7R44Kkx3xB8Jxv4FVr5I5YkWQJAsh4n9SoTo98vX7KJz/8Alxk5rS+e0yZE3zJNgaOctP89bu5A0S1OkgKyUL2aTXX/9IPd8i6Q99J31kCd4GZU1cqjQvwifYEY93txNcRCYuF/x5u8JaDCZl689qNq672PiOcsUIZEEn2Op4au5Veo1JhFN+fRKNFo9RAg2tyfRCFm1T76ShkUmS8+9fhGE7Tx6hH1ZioJxoqhKPmtqMEdLDCaoZkrvIo5l7tW+bpZYlFaG6ohm/93AZ3DQlDeAtD11KTSPuqvmL54TvXZ89SImNf4NtSnT8b73D1+Gds0UH/UwNNB2WjtRHCGh0Bgg8uZjvgCyo7XMUyoQw9QdwMGKeBvw30pwSUKev6derW3QycunH/tIaqVNs3Ma7XykUDWwlyFkcLiaaRdzGKY08F5QBhcZcJ9F0txXVf1Wa2WJH25x1B8t9BvqwRTzbkSKNajdS6S1sgtVFdhG8m/gfbchsS1OyFJHTnI6d96xCTQowQCGnfMQV+hYHuQ1yCseLyh0p2+NzjG2xQQ5ybyf2cZHIPjtZtxvxkr3it2AMl2tuXv2E4CcnjG+oUeNaHecroXfeZrgpteUOQ4KMicVbxPBqGgZ9nWVF+3KLO4JIHa+ByY/bT4="
